#!/bin/bash

MCPATH=${HOME}/bin/config/mc.config

if [ ! -f ${MCPATH} ]; then
	echo "Error: There is no ${MCPATH} file!"
	exit
fi

. ${MCPATH}
# mc.config has 3 variables: 
#  SAVE_DIR - path to saves directory eg. SAVEDIR=/home/kruz/games/minecraft/saves/
#  BACKUP_DIR - path to backup the files eg. /mnt/backups/minecraft/
#  WORLD_NAME - name of world eg. WORLD_NAME="New World"

if [ -z "${SAVE_DIR}" ]; then
	echo "SAVE_DIR variable not configured in ${MCPATH}"
	exit
fi

if [ -z "${BACKUP_DIR}" ]; then
	echo "BACKUP_DIR variable not configured in ${MCPATH}"
	exit
fi

if [ -z "${WORLD_NAME}" ]; then
	echo "WORLD_NAME variable not configured in ${MCPATH}"
	exit
fi

echo "Backing up $WORLD_NAME ..."
rsync -avP "${SAVE_DIR}/$WORLD_NAME/" "${BACKUP_DIR}/${WORLD_NAME}/"
zip -r ${BACKUP_DIR}/${WORLD_NAME}-$(date +"%Y%m%d%H%M%S").zip "${BACKUP_DIR}/${WORLD_NAME}"
